### ISSUE TITLE
`apt install qemu` installs dummy package

### ISSUE THREAD

**Issue by tynovsky** [littleli/boot2plasma#2]
I followed the README and did

`sudo apt install qemu`

on Ubuntu. But it only installed dummy package. `apt show qemu` says

> current `qemu' package makes no sense anymore, and is becoming a dummy package.

The correct package is `qemu-system-i386`. Please fix the doc.

**Comment by littleli** [comment]
I updated README. Installation instructions are now pointing to official guides.
